services:
  db-postgre:
    container_name: postgres-container
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: root
      POSTGRES_DB: novel
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
